version: '3'

services: 
  app:
    image: wekkwekk/docker-full-stack-app:1.0
    ports:
      - "3000:3000"
    volumes: 
      - myvolume99:/usr/src/app
        
    restart: always
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"

volumes: 
  myvolume99:
